/**
 * Vercel Catch-All API Function
 *
 * Loads the pre-bundled Express application generated by api/build.mjs.
 * The bundle contains the workspace API dependencies so Vercel does not
 * attempt to resolve workspace TypeScript source files at runtime.
 */

import app from "./.vercel-build/app.mjs";

export const config = {
  api: {
    bodyParser: false,
  },
};

export default app;
