// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/promo-banner/Preview.tsx": () => import("../components/mockups/promo-banner/Preview.tsx")
};
